<?php

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_region().
 */
function motollantas_preprocess_region(&$variables) {
  if (isset($variables['region'])) { 
    switch ($variables['region']) {
      case 'footer':
      case 'footer_bottom':
        $variables['attributes']['class'][] = 'container';
          break;
    }
  }
}